### PR TITLE
Update playfair include

### PR DESCRIPTION
**Pull request by thiccaxe**

### CODE REVIEW

**Comment by fduncanh** [comment]
why do we need the initial fairplay?

we are already in directory fairplay,  so the include is in  playfair/playfair.h  relative to directory fairplay?

**Comment by fduncanh** [comment]
It builds either way for me

**Comment by thiccaxe** [comment]
it does not build for me consitently\* without it. Furthermore, the playfair code doesn't actually get included in the demo build unless the import is updated.


\*
- only builds when in the root directory or a subdirectory of the root, ie:
```
apsdk-public/
      -> builds here OK
      .build/linux/
              -> builds here OK
apsdk-public-build/
      -> builds here NOT OK

**Comment by thiccaxe** [comment]
> why do we need the initial fairplay?

I honestly do not have a good answer. But, this is what IntelliJ Clion made the import as when I removed the old import and CLion auto-imported the decryption function.

**Pull request merged**
